// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sayhi.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bye_Number int32

const (
	Bye_ONE Bye_Number = 0
	Bye_TWO Bye_Number = 1
)

var Bye_Number_name = map[int32]string{
	0: "ONE",
	1: "TWO",
}

var Bye_Number_value = map[string]int32{
	"ONE": 0,
	"TWO": 1,
}

func (x Bye_Number) String() string {
	return proto.EnumName(Bye_Number_name, int32(x))
}

func (Bye_Number) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_58f0dc26e679a096, []int{2, 0}
}

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_58f0dc26e679a096, []int{0}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type Hello struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Num                  int64    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_58f0dc26e679a096, []int{1}
}

func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (m *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(m, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hello) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Hello) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type Bye struct {
	Num                  Bye_Number `protobuf:"varint,1,opt,name=num,proto3,enum=grpc.Bye_Number" json:"num,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Bye) Reset()         { *m = Bye{} }
func (m *Bye) String() string { return proto.CompactTextString(m) }
func (*Bye) ProtoMessage()    {}
func (*Bye) Descriptor() ([]byte, []int) {
	return fileDescriptor_58f0dc26e679a096, []int{2}
}

func (m *Bye) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bye.Unmarshal(m, b)
}
func (m *Bye) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bye.Marshal(b, m, deterministic)
}
func (m *Bye) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bye.Merge(m, src)
}
func (m *Bye) XXX_Size() int {
	return xxx_messageInfo_Bye.Size(m)
}
func (m *Bye) XXX_DiscardUnknown() {
	xxx_messageInfo_Bye.DiscardUnknown(m)
}

var xxx_messageInfo_Bye proto.InternalMessageInfo

func (m *Bye) GetNum() Bye_Number {
	if m != nil {
		return m.Num
	}
	return Bye_ONE
}

func (m *Bye) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("grpc.Bye_Number", Bye_Number_name, Bye_Number_value)
	proto.RegisterType((*Null)(nil), "grpc.Null")
	proto.RegisterType((*Hello)(nil), "grpc.Hello")
	proto.RegisterType((*Bye)(nil), "grpc.Bye")
}

func init() { proto.RegisterFile("sayhi.proto", fileDescriptor_58f0dc26e679a096) }

var fileDescriptor_58f0dc26e679a096 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x1b, 0x53, 0x3b, 0x77, 0x07, 0x5a, 0xf2, 0x62, 0xe9, 0xd3, 0x88, 0x08, 0x7b, 0x90,
	0x20, 0xf3, 0x07, 0x08, 0x05, 0xd1, 0xa7, 0x6e, 0x6c, 0x4a, 0x9f, 0xbb, 0x79, 0x59, 0x0b, 0xc9,
	0x32, 0xd2, 0x95, 0x91, 0x7f, 0x2f, 0x37, 0x01, 0x11, 0x7c, 0xfb, 0xee, 0xc9, 0xcd, 0xc9, 0xc9,
	0x81, 0xd9, 0xd0, 0xfa, 0xae, 0x57, 0x27, 0x67, 0xcf, 0x56, 0xa4, 0x07, 0x77, 0xda, 0xcb, 0x0c,
	0xd2, 0x7a, 0xd4, 0x5a, 0xbe, 0xc2, 0xf5, 0x07, 0x6a, 0x6d, 0x85, 0x80, 0xf4, 0xd8, 0x1a, 0x2c,
	0xd8, 0x9c, 0x2d, 0xa6, 0x9b, 0xc0, 0x22, 0x07, 0x6e, 0x86, 0x43, 0x71, 0x15, 0x24, 0x42, 0x52,
	0x8e, 0xa3, 0x29, 0xf8, 0x9c, 0x2d, 0xf8, 0x86, 0x50, 0x36, 0xc0, 0x2b, 0x8f, 0x42, 0xc6, 0x03,
	0xba, 0x7d, 0xbb, 0xcc, 0x15, 0xbd, 0xa1, 0x2a, 0x8f, 0xaa, 0x1e, 0xcd, 0x0e, 0x5d, 0x58, 0xfd,
	0x6f, 0x27, 0x4b, 0xc8, 0xe2, 0x82, 0x98, 0x00, 0x5f, 0xd5, 0x6f, 0x79, 0x42, 0xf0, 0xd9, 0xac,
	0x72, 0xb6, 0xfc, 0x82, 0xc9, 0xbb, 0x43, 0x3c, 0xa3, 0x13, 0x8f, 0x70, 0xb3, 0x6d, 0x7d, 0xcc,
	0x39, 0x8b, 0xde, 0x61, 0x28, 0x21, 0x0e, 0xe1, 0x27, 0x89, 0x78, 0x80, 0x6c, 0xdb, 0x7a, 0x4a,
	0xf3, 0x47, 0x2f, 0xa7, 0xbf, 0x61, 0x64, 0xf2, 0xcc, 0xaa, 0x27, 0xb8, 0xdf, 0x5b, 0xa3, 0x2e,
	0xfd, 0xd0, 0xe9, 0x5e, 0x7b, 0xd5, 0x91, 0xd1, 0xc5, 0x3a, 0xfd, 0x5d, 0xdd, 0x05, 0xd3, 0x86,
	0x78, 0x4d, 0x55, 0xad, 0x93, 0x5d, 0x16, 0x3a, 0x7b, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0x65,
	0x96, 0x5a, 0xfb, 0x42, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*Null, error)
	SayBye(ctx context.Context, in *Null, opts ...grpc.CallOption) (Greeter_SayByeClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*Null, error) {
	out := new(Null)
	err := c.cc.Invoke(ctx, "/grpc.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayBye(ctx context.Context, in *Null, opts ...grpc.CallOption) (Greeter_SayByeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/grpc.Greeter/SayBye", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayByeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayByeClient interface {
	Recv() (*Bye, error)
	grpc.ClientStream
}

type greeterSayByeClient struct {
	grpc.ClientStream
}

func (x *greeterSayByeClient) Recv() (*Bye, error) {
	m := new(Bye)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	SayHello(context.Context, *Hello) (*Null, error)
	SayBye(*Null, Greeter_SayByeServer) error
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*Hello))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayBye_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Null)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayBye(m, &greeterSayByeServer{stream})
}

type Greeter_SayByeServer interface {
	Send(*Bye) error
	grpc.ServerStream
}

type greeterSayByeServer struct {
	grpc.ServerStream
}

func (x *greeterSayByeServer) Send(m *Bye) error {
	return x.ServerStream.SendMsg(m)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayBye",
			Handler:       _Greeter_SayBye_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sayhi.proto",
}
